context: minikube

name: streams-nodejs

dev:
  streams-nodejs:
    image: node:18
    imagePullPolicy: Never
    namespace: fraym
    command: bash

    workdir: /code
    sync:
      - .:/code
      - $HOME/.ssh:/root/.ssh
    secrets:
      - $HOME/.npmrc:/root/.npmrc
