name: Streams nodejs client - CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: ["18"]
    name: Node ${{ matrix.node }} Testing
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}
          registry-url: "https://registry.npmjs.org"
      - name: Cache node modules
        uses: actions/cache@v2
        env:
          cache-name: cache-node-modules
        with:
          path: "**/node_modules"
          key: ${{ matrix.node }}-modules-${{ hashFiles('**/package-lock.json') }}
      - name: NPM Install
        run: npm install
      - name: Lint
        run: npm run-script lint
      - name: NPM Test
        run: npm test
      - name: Build lib
        run: npm run-script build
      - name: NPM Audit
        run: npm audit --production
