name: Streams nodejs client - CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: ["18"]
    name: Node ${{ matrix.node }} Testing
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}
          registry-url: "https://registry.npmjs.org"
          cache: "npm"
      - name: NPM Install
        run: npm ci
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      - name: Lint
        run: npm run lint
      - name: NPM Test
        run: npm test
      - name: Build lib
        run: npm run build
      - name: NPM Audit
        run: npm audit --production
